export const employees_datas = [
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },

  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User1",
    lastName: "Test1",
    dateOfBirth: "09/08/2022",
    startDate: "10/27/2022",
    department: "Engineering",
    street: "45 rue de l'utilisateur",
    city: "New City",
    state: "AL",
    zipCode: "34567",
  },
  {
    firstName: "User2",
    lastName: "Test2",
    dateOfBirth: "09/11/2022",
    startDate: "10/27/2023",
    department: "Human Resources",
    street: "46 rue de l'utilisateur",
    city: "New Town",
    state: "CA",
    zipCode: "34999",
  },
  {
    firstName: "User2",
    lastName: "Test2",
    dateOfBirth: "09/11/2022",
    startDate: "10/27/2023",
    department: "Human Resources",
    street: "46 rue de l'utilisateur",
    city: "New Town",
    state: "CA",
    zipCode: "34999",
  },
  {
    firstName: "User2",
    lastName: "Test2",
    dateOfBirth: "09/11/2022",
    startDate: "10/27/2023",
    department: "Human Resources",
    street: "46 rue de l'utilisateur",
    city: "New Town",
    state: "CA",
    zipCode: "34999",
  },
  {
    firstName: "User2",
    lastName: "Test2",
    dateOfBirth: "09/11/2022",
    startDate: "10/27/2023",
    department: "Human Resources",
    street: "46 rue de l'utilisateur",
    city: "New Town",
    state: "CA",
    zipCode: "34999",
  },
  {
    firstName: "User2",
    lastName: "Test2",
    dateOfBirth: "09/11/2022",
    startDate: "10/27/2023",
    department: "Human Resources",
    street: "46 rue de l'utilisateur",
    city: "New Town",
    state: "CA",
    zipCode: "34999",
  },
  {
    firstName: "ZZZZ",
    lastName: "AAA1",
    dateOfBirth: "09/30/2008",
    startDate: "09/28/2022",
    department: "Sales",
    street: "1 rue ",
    city: "aaa",
    state: "AR",
    zipCode: "",
  },
  {
    firstName: "auser",
    lastName: "alastname",
    dateOfBirth: "12/09/2001",
    startDate: "02/05/2006",
    department: "Sales",
    street: "21",
    city: "Kuala-Lumpur",
    state: "MO",
    zipCode: "00000",
  },
  {
    firstName: "auser",
    lastName: "alastname",
    dateOfBirth: "12/09/2001",
    startDate: "02/05/2006",
    department: "Sales",
    street: "21",
    city: "Kuala-Lumpur",
    state: "MO",
    zipCode: "00000",
  },
  {
    firstName: "auser",
    lastName: "alastname",
    dateOfBirth: "12/09/2001",
    startDate: "02/05/2006",
    department: "Sales",
    street: "21",
    city: "Kuala-Lumpur",
    state: "MO",
    zipCode: "00000",
  },
]

export const options = [
  { value: "Sales", label: "Sales" },
  { value: "Marketing", label: "Marketing" },
  { value: "Engineering", label: "Engineering" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "Legal", label: "Legal" },
]

export const states = [
  {
    label: "Alabama",
    value: "AL",
  },
  {
    label: "Alaska",
    value: "AK",
  },
  {
    label: "American Samoa",
    value: "AS",
  },
  {
    label: "Arizona",
    value: "AZ",
  },
  {
    label: "Arkansas",
    value: "AR",
  },
  {
    label: "California",
    value: "CA",
  },
  {
    label: "Colorado",
    value: "CO",
  },
  {
    label: "Connecticut",
    value: "CT",
  },
  {
    label: "Delaware",
    value: "DE",
  },
  {
    label: "District Of Columbia",
    value: "DC",
  },
  {
    label: "Federated States Of Micronesia",
    value: "FM",
  },
  {
    label: "Florida",
    value: "FL",
  },
  {
    label: "Georgia",
    value: "GA",
  },
  {
    label: "Guam",
    value: "GU",
  },
  {
    label: "Hawaii",
    value: "HI",
  },
  {
    label: "Idaho",
    value: "ID",
  },
  {
    label: "Illinois",
    value: "IL",
  },
  {
    label: "Indiana",
    value: "IN",
  },
  {
    label: "Iowa",
    value: "IA",
  },
  {
    label: "Kansas",
    value: "KS",
  },
  {
    label: "Kentucky",
    value: "KY",
  },
  {
    label: "Louisiana",
    value: "LA",
  },
  {
    label: "Maine",
    value: "ME",
  },
  {
    label: "Marshall Islands",
    value: "MH",
  },
  {
    label: "Maryland",
    value: "MD",
  },
  {
    label: "Massachusetts",
    value: "MA",
  },
  {
    label: "Michigan",
    value: "MI",
  },
  {
    label: "Minnesota",
    value: "MN",
  },
  {
    label: "Mississippi",
    value: "MS",
  },
  {
    label: "Missouri",
    value: "MO",
  },
  {
    label: "Montana",
    value: "MT",
  },
  {
    label: "Nebraska",
    value: "NE",
  },
  {
    label: "Nevada",
    value: "NV",
  },
  {
    label: "New Hampshire",
    value: "NH",
  },
  {
    label: "New Jersey",
    value: "NJ",
  },
  {
    label: "New Mexico",
    value: "NM",
  },
  {
    label: "New York",
    value: "NY",
  },
  {
    label: "North Carolina",
    value: "NC",
  },
  {
    label: "North Dakota",
    value: "ND",
  },
  {
    label: "Northern Mariana Islands",
    value: "MP",
  },
  {
    label: "Ohio",
    value: "OH",
  },
  {
    label: "Oklahoma",
    value: "OK",
  },
  {
    label: "Oregon",
    value: "OR",
  },
  {
    label: "Palau",
    value: "PW",
  },
  {
    label: "Pennsylvania",
    value: "PA",
  },
  {
    label: "Puerto Rico",
    value: "PR",
  },
  {
    label: "Rhode Island",
    value: "RI",
  },
  {
    label: "South Carolina",
    value: "SC",
  },
  {
    label: "South Dakota",
    value: "SD",
  },
  {
    label: "Tennessee",
    value: "TN",
  },
  {
    label: "Texas",
    value: "TX",
  },
  {
    label: "Utah",
    value: "UT",
  },
  {
    label: "Vermont",
    value: "VT",
  },
  {
    label: "Virgin Islands",
    value: "VI",
  },
  {
    label: "Virginia",
    value: "VA",
  },
  {
    label: "Washington",
    value: "WA",
  },
  {
    label: "West Virginia",
    value: "WV",
  },
  {
    label: "Wisconsin",
    value: "WI",
  },
  {
    label: "Wyoming",
    value: "WY",
  },
]
